In [1]:
import numpy as np

In [5]:
a = np.matrix([[0,-1],[3,4],[0,2]])

In [6]:
a

matrix([[ 0, -1],
        [ 3,  4],
        [ 0,  2]])

In [8]:
a.shape

(3, 2)

### Elementry Row Operations
1. Swapping Rows
2. Multiplying row by a constant
3. Multiplying a row by a constant and adding it to a second row

In [9]:
np.dot([1,7,9,11],[7,1,2,2])

54

In [10]:
import math
math.hypot(3,4)

5.0

In [12]:
A = np.matrix([[1,1],[20,25]])
b = np.matrix([[30],[690]])

np.linalg.solve(A,b)

# import scipy.linalg as la -> la.solve(A,b)

matrix([[12.],
        [18.]])

### LA Text

Basic matrix notation:

$$ 
\left[
\begin{matrix}
    1   & 0 & 4  \\
    0   & 2 & -2  \\
    0   & 1 & 2 
\end{matrix}
\right] 
$$

Augmented matrix notation:

$$ 
\left[
\begin{matrix}
    1   & 0 & 4  \\
    0   & 2 & -2  \\
    0   & 1 & 2 
 \end{matrix}
\, \middle\vert \,
\begin{matrix}
-10 \\ 3 \\ 1
\end{matrix}
\right] 
$$

$$ c = \sqrt{a^2 + b^2} $$

In [18]:
# Same A, multiple b

w = np.matrix([[1,1],[20,25]])
w1 = np.matrix([[30],[690]])
w2 = np.matrix([[35],[750]])
w3 = np.matrix([[30],[650]])

b = np.concatenate((w1,w2,w3),axis = 1)
np.linalg.solve(w,b)

matrix([[12., 25., 20.],
        [18., 10., 10.]])

System of linear equations is homogenous if all constant terms are 0


### Three steps to Gauss-Jordan Elimination
1. Start with augmented matrix of the system of linear equations
2. Derive the reduced echelon form of the augmented matrix using elementary row operations. This is done by creating leadings 1s, then zeros above and below each of the leading 1, column by column starting with the first
3. Write down the system of equations corresponding to the reduced echelon form. This system gives the solution

### RREF vs REF
1. REF:
    1. All nonzeros rows are above any rows of all zeros
    2. Each leading entry of a row is in a column to the right of the leading entry of the row above it
    3. All entries in a column below a leading entry are zeros
2. RREF
    1. Matrix in REF form
    2. Each leading 1 is the only nonzero entry in its column
    

The following are properties of vector addition and multiplication for vectors $u$ and $v$:

1. $u + v = v + u$ Commutative property
2. $u + (v + w) = (u + v) + w$ Associative property
3. $u+0 = 0 + u = u$ Property of zero vector
4. $u + (-u) = 0$ Property of the negative vector
5. $c(u+v) = cu + cv$ Distributive properties
6. $(c+d)u = cu+du$ Distributive Properties
7. $c(du) = (cd)u$ Distributed Properties
8. $1u = u$ Scalar multiplication by 1

In [22]:
import sympy as sym
sym.init_printing(use_unicode=True) # Trick to make matrixes look nice in jupyter

sym.Matrix(A)

⎡1   1 ⎤
⎢      ⎥
⎣20  25⎦

In [24]:
A = np.matrix([[3,-3,9],[2,-2,7],[-1,2,-4]])
sym.Matrix(A)

⎡3   -3  9 ⎤
⎢          ⎥
⎢2   -2  7 ⎥
⎢          ⎥
⎣-1  2   -4⎦

In [25]:
# Matrix swap row 3 with row 1
E = np.matrix([[0,0,1],[0,1,0],[1,0,0]])
sym.Matrix(E*A)

⎡-1  2   -4⎤
⎢          ⎥
⎢2   -2  7 ⎥
⎢          ⎥
⎣3   -3  9 ⎦

In [27]:
# Matrix multiply first row by c = 3 and adds it to the third row
E = np.matrix([[1,0,0],[0,1,0],[3,0,1]])
sym.Matrix(E*A)

⎡3  -3  9 ⎤
⎢         ⎥
⎢2  -2  7 ⎥
⎢         ⎥
⎣8  -7  23⎦

----
# 3. The Inverse Matrix (aka $A^{-1}$)

For some (not all) **square** matrices $A$, there exists a special matrix called the Inverse Matrix, which is typically written as $A^{-1}$ and when multiplied by the $A$ results in the Identity matrix $I$:

$$ A^{-1}A = AA^{-1} = I $$

Some properties of a Matrix Inverse Include:

1. $(A^{-1})^{-1} = A$
2. $(cA)^{-1} = \frac{1}{c}A^{-1}$
3. $(AB)^{-1} = B^{-1}A^{-1}$
4. $(A^n)^{-1} = (A^{-1})^n$
1. $(A^t)^{-1} = (A^{-1})^t$

Other fun facts
1. Invertable matrix is always square
2. A square matrix is not always invertable
3. RREF of a square invertible matrix is an identity matrix


In [30]:
A_inv = np.linalg.inv(A)
sym.Matrix(A_inv)

⎡       2.0          -2.0  1.0⎤
⎢                             ⎥
⎢-0.333333333333333  1.0   1.0⎥
⎢                             ⎥
⎣-0.666666666666667  1.0   0.0⎦

In [31]:
sym.Matrix(A*A_inv)

⎡        1.0           0.0  0.0⎤
⎢                              ⎥
⎢8.88178419700125e-16  1.0  0.0⎥
⎢                              ⎥
⎣        0.0           0.0  1.0⎦

In [32]:
sym.Matrix(A)

⎡3   -3  9 ⎤
⎢          ⎥
⎢2   -2  7 ⎥
⎢          ⎥
⎣-1  2   -4⎦

In [33]:
sym.Matrix(A.T)

⎡3   2   -1⎤
⎢          ⎥
⎢-3  -2  2 ⎥
⎢          ⎥
⎣9   7   -4⎦



$$
\left[
\begin{matrix}
    \sin{(\theta)} & -\cos{(\theta)} & 0 & d_x \\ 
    \cos{(\theta)} & \sin{(\theta)}  & 0 & d_y \\ 
    0 & 0  & 1 & d_z \\ 
    0 & 0  & 0 & 1 
\end{matrix}
\right] 
$$

$$ 
\left[ \begin{matrix}
    x_{end} \\
    y_{end} 
 \end{matrix}
\right] 
=
\left[ \begin{matrix}
    \cos(q) & -\sin(q) \\
    \sin(q) & \cos(q) 
 \end{matrix}
\right] 
\left[ \begin{matrix}
    x_{start} \\
    y_{start} 
 \end{matrix}
\right] 
$$ 

In [35]:
np.linalg.det(A)

## Determinant Tricks

Some interesting properties of determinants result in applying elementary row operations. For example, let $A$ be an $n \times n$ matrix and $c$ be a nonzero scalar.

1. If a matrix $B$ is obtained from $A$ by multiplying a row (column) by $c$ then $|B| = c|A|$.
2. If a matrix $B$ is obtained from $A$ by interchanging two rows (columns) then $|B| = -|A|$.
3. if a matrix $B$ is obtained from $A$ by adding a multiple of one row (column) to another row (column), then $|B| = |A|$.

## Theorem 3.3 - Singular Matrices

**Definition:** A square matrix $A$ is said to be **singular** if $|A| = 0$. $A$ is **nonsingular** if $|A| \neq 0$

Now, Let $A$ be an $n \times n$ matrix. $A$ is singular if:

1. all the elements of a row (column) are zero.
2. two rows (columns) are equal.
3. two rows (columns) are proportional. i.e. they are the same given a scalar $c$.

Let $A$ and $B$ be $n\times n$ matrices and $c$ be a nonzero scalar.

1. Determinate of a scalr multiple: $|cA| = c^n|A|$
2. Determinate of a product: $|AB| = |A||B|$
3. Determinate of a transpose" $|A^t| = |A|$
4. Determinate of an inverse: $|A^{-1}| = \frac{1}{|A|}$ (Assuming $A^{-1}$ exists)

The determinate of an *upper triangle matrix* is the product of the diagonal elements of the matrix $A$.  

Also, per Theorem 3.4.3 the determinate of a *lower triangle matrix* is also the product of the diagonal elements. 

**LINEAR RULES:**
$$F(cx) = cF(x)$$
$$F(x+y) = F(x)+F(y)$$


----
# 3. Jacobi Method for Solving Linear Systems 01 inclass

As a group, we will write an iterative method (named after Jacobi) to solve the following system of equations:

$$ 6x + 2y - z = 4$$
$$ x + 5y + z = 3$$
$$ 2x + y + 4z = 27$$

Here is a basic outline of the Jacobi method:

1. Initialize each of the variables to zero ($x_0 = 0, y_0 = 0, z_0 = 0$) 
2. Calculate the next iteration using the above equations and the values from the previous iteration. For example the formula for calculating $x_i$ from $y_{(i-1)}$ and $z_{(i-1)}$ is:
    $$x_i = \frac{4 - 2y_{(i-1)} + z_{(i-1)}}{6} $$
3. Increment the iteration count $(i = i + 1)$ and repeat step 2.
4. Stop when the iteration "converges" or a maximum number (ex. 100) of iterations has been reached.

**IMPORTANT NOTE:** This method does not work for all systems of linear equations.  From **Theorem 7.1** in the book, we know that the Jacobi method can be used when the absolute value of the diagonal element of each row **dominate** the sum of the absolute values for the other elements in the same row. 
 
 
 
 **Do This:** On a paper, write out the equations for $x_i, y_i$, and $z_i$ based on $x_{(i-1)}, y_{(i-1)}$, and $z_{(i-1)}$.  Show your answer to an instructor:
 
 $$x_i = \frac{4 - 2y_{(i-1)} + z_{(i-1)}}{6} $$
 $$y_i = \frac{3 - x_{(i-1)} - z_{(i-1)}}{5} $$
 $$z_i = \frac{27 - 2x_{(i-1)} - y_{(i-1)}}{4} $$



In [39]:
# Curve Fitting 02 Inclass
def fitPoly3(p1,p2,p3,p4):
    A = np.matrix([[p1[0]**3, p1[0]**2, p1[0], 1],
                   [p2[0]**3, p2[0]**2, p2[0], 1],
                   [p3[0]**3, p3[0]**2, p3[0], 1],
                   [p4[0]**3, p4[0]**2, p4[0], 1]])
    
    b = np.matrix([p1[1],p2[1],p3[1],p4[1]]).T

    X = np.linalg.solve(A, b)
    a = X.item(0)
    b = X.item(1)
    c = X.item(2)
    d = X.item(3)
    
    #Try putting your figure generation code here
    x = np.linspace(-3,3)
    y = a*x**3 + b*x**2 + c*x + d

    #plot the function. (Transpose is needed to make the data line up).
    plt.plot(x,y.transpose())

    #Plot the original points
    plt.scatter(p1[0],p1[1])
    plt.scatter(p2[0],p2[1])
    plt.scatter(p3[0],p3[1])
    plt.scatter(p4[0],p4[1])
    plt.xlabel('x-axis')
    plt.ylabel('y-axis')
    
    return (a,b,c,d)


In [41]:
# Gaussian Elimination - 3b inclass

def divide_row_to_get_one(vector,c):
    constant = vector[c]
    for e in range(0,len(vector)):
        vector[e]=vector[e]/constant
    return vector
        
def zero_out_column_below(matrix,r,c):
    columns_in_matrix = len(matrix[0])
    rows_in_matrix = len(matrix)
    if(matrix[r][c] != 1):
        print('ERROR - this should always be 1')
    ### Put YOUR CODE HERE
    ### The difference between this function and zero_out_colum is that
    ### this function zeros out only the lower left part of the matrix.
    for e_r in range(r, rows_in_matrix):
        if e_r != r:
            constant = -matrix[e_r][c]
            for e_c in range(columns_in_matrix):
                if (matrix[r][e_c] != 0):
                    matrix[e_r][e_c] = matrix[r][e_c] * constant + matrix[e_r][e_c]
                
        
    return matrix

def zero_out_column_above(matrix,c):
    ### Put YOUR CODE HERE
    ### This function puts rows from 0 to c-1 (total c rows) on column c to be zero. 
    ### (Note that the index in python starts from 0)
    r = c
    columns_in_matrix = len(matrix[0])
    rows_in_matrix = len(matrix)
    if(matrix[r][c] != 1):
        print('ERROR - this should always be 1')
    for e_r in range(r):
        if e_r != r:
            constant = -matrix[e_r][c]
            for e_c in range(columns_in_matrix):
                if (matrix[r][e_c] != 0):
                    matrix[e_r][e_c] = matrix[r][e_c] * constant + matrix[e_r][e_c]
    
    
    return matrix


def rref_Gauss(matrix):
    columns_in_matrix = len(matrix[0])
    rows_in_matrix = len(matrix)
    for c in range(columns_in_matrix):
        r = 0
        pivot=False
        for r in range(c,rows_in_matrix):
            if matrix[r][c] != 0:
                pivot = True
                break
        if pivot:
            if(r != c):
                #Swap_rows
                temp = matrix[r]
                matrix[r] = matrix[c]
                matrix[c] = temp
                r = c
            matrix[r] = divide_row_to_get_one(matrix[r],c)
            matrix = zero_out_column_below(matrix,r,c)
    for c in range(rows_in_matrix-1, 0, -1):
        zero_out_column_above(matrix,c)
    
    return matrix



## X-Axis rotation 06 inclass

$$ 
\left[ \begin{matrix}
    x' \\
    y' \\
    z' \\
    1 
 \end{matrix}
\right] 
=
\left[ \begin{matrix}
    1 & 0 & 0 & dx \\
    0 & cos(q) & -sin(q)  & dy \\
    0 & sin(q) & cos(q)  & dz \\
    0 & 0 & 0 & 1
 \end{matrix}
\right] 
\left[ \begin{matrix}
    x \\
    y \\
    z \\
    1 
 \end{matrix}
\right] 
$$ 



# 3. Systems of Linear Equations with Many Solutions In class 07

When we solve a system of equations, we mentioned that we may have three outcomes: unique solution, no solution (inconsistent), infinity many solutions. 

**A system is inconstent means that $b$ is not in the sub space spanned by all the columns**

Assume that we have $m$ equations and $n$ unkowns. 

**Case 1** $m< n$, we do not have enough equations, there will be only two outcomes: no solution, or infinity many solutions. 

**Case 2** $m= n$, we may have all three outcomes. If the determinate is nonzero, we have unique solution, otherwise, we have to decide the outcome based on augmented matrix. 

**Case 3** $m>n$, we have more equations than the number of unknowns. That means there will be redundant equations (we can remove them) or conflict equations (no solution). We may have all three outcomes. 


### 1.6 Dot Product, Norm, Angle, and Distance
* Be able to calculate the dot produt between two vectors $u$ and $v$

$$ u \cdot v = u_1v_1+ \dots + u_n v_n $$

* Calculate the norm of a vector in $R^n$

$$  \|u\| = \sqrt{u_1^2 +  \dots + u_n^2} \text{    or    } \|u\| = \sqrt{u \cdot u} $$

* Angle between two vectors

$$ cos(\theta) = \frac{u \cdot v}{ \|u\| \|v\| }$$

* Distance between two points $x$ and $y$

$$d(x,y) = \sqrt{x_1-y_1)^2 + \dots + (x_n-y_n)^2}= \|x-y\|$$


- LU Decomposition: $A = LU$
- Cholesky Decomposition: $A = R^TR\quad (= LDL^T)$
    - This factorization of $A$ into $R^TR$ also requires that $A$ be *symmetric* and *positive-definite*. The latter term simply requires that $x^{T}Ax > 0$ for every nonzero $x \in \mathbb{R}^n$. If it is not obvious, you should confirm that $x^{T}Ax$ is always some scalar value (e.g., note that $x^TA = y^T$ for some vector $y\in\mathbb{R}^n$, and $y^Tx$ is the dot product between $x$ and $y$ and, hence, a real scalar).
    
Each matrix in these decompositions is the *matrix product* of <a href="https://en.wikipedia.org/wiki/Elementary_matrix">elementary matrices</a>. 
Recall that *an elementary matrix differs from the identity matrix (the square matrix with $1$s on the diagonal and $0$s elsewhere) by an elementary row operation*.
 
The use of these matrix decompositions in Numerical Linear Algebra is motivated by computational efficiency or reduction of *computational complexity* (recall "**Big-O notation**" and **counting the loops in your matrix multiplication algorithm**) and *numerical stability*. 
Solving our old friend $Ax = b$ by computing the inverse of $A$, denoted $A^{-1}$, and taking the matrix-vector product $A^{-1}b = x$ is computational resource intensive and numerically unstable, in general. 
If the $LU$ decomposition of $A$ exists, then it will be less costly and more stable to:
1. Solve $Ly = b$ for $y$ by *forward-substitution*; and then
2. Solve $Ux = y$ for $x$ by *backward-substitution*


In [45]:
A.T*A

matrix([[ 14, -15,  45],
        [-15,  17, -49],
        [ 45, -49, 146]])

In [46]:
A

matrix([[ 3, -3,  9],
        [ 2, -2,  7],
        [-1,  2, -4]])

In [53]:
sym.Matrix(A).rref()

⎛⎡1  0  0⎤           ⎞
⎜⎢       ⎥           ⎟
⎜⎢0  1  0⎥, (0, 1, 2)⎟
⎜⎢       ⎥           ⎟
⎝⎣0  0  1⎦           ⎠