## <p style="text-align: right;"> &#9989; Nic Wiggins</p>

You **NEED** to participate both individually and in groups in class to successfully complete this assignment and receive credits for it.

# In-Class Assignment: Portfolio Optimization

<img src="https://www.mathworks.com/company/newsletters/articles/developing-portfolio-optimization-models/_jcr_content/mainParsys/image_0.adapt.full.high.jpg/1469941490053.jpg" width="50%">
</p>


### Agenda for today's class (80 minutes)

</p>
1. (25 minutes) Portfolio Pre-class Review
1. (50 minutes) Portfolios with Three Risky Assets

---
# 1. Portfolio Pre-class Review
[20--Portfolio_Optimization-pre-class-assignment](../preclass/20--Portfolio_Optimization-pre-class-assignment.ipynb)

----

# 2. Portfolios with Three Risky Assets

We consider a small problem with only three assets denoted $1$, $2$, and $3$. 
Let $R_i(i=1,2,3)$ be the random return on the assets (when we invest, we can not make sure that we will earn money, there is alway risk).

**Example:** The following table give the monthly means, variance and covariances for the continuously compounded returns on three stocks over five year. 

| Stock $i$  | $\mu_i$ | $\sigma_i$ | Pair $(i,j)$ | $\sigma_{ij}$ |
|---|---|---|---|---|
| Microsoft (1) | 0.0427 | 0.1 | (1,2) | 0.0018 | 
| Nordstrom (2) | 0.0015 | 0.1044 | (1,3) | 0.0011 | 
| Starbucks (3) | 0.0285 | 0.1411 | (2,3) | 0.0026 | 

+ The second column shows the expected return for each month. We can see that the expected return for Starbucks is the largest. 
+ The third column shows the variance on the return for each stock. If the variance is big, then you may have a higher probability to earn less than (or loss) the expected value. 
+ The fourth and the fifth column shows the covariance between these stocks. There are some connections between the stocks and the increase of one stock has relations to the increase of another.

We want to earn more money but we do not want too big risk. How do we choose a portflio (how to distributed the inverstment?)

Let $x=(x_1,x_2,x_3)$ denote the distribution of your investment on these three stocks. 
Assume that you have to invest all the money, and you can not borrow money. 
That is $x_1+x_2+x_3=1$ (Note that we can choose negative values so we can short some stocks). 

The expected return is computed as 
$$\mu = x_1 \mu_1 + x_2 \mu_2 + x_3 \mu_3.$$
The risk is computed as 
$$\sigma = x_1^2\sigma_1^2+x_2^2\sigma_2^2+x_3^2\sigma_3^2+2x_1x_2\sigma_{12}+2x_2x_3\sigma_{23}+2x_1x_3\sigma_{13}$$

In [1]:
%matplotlib inline
import matplotlib.pylab as plt
import numpy as np
import sympy as sym
import time
sym.init_printing(use_unicode=True)

<font color=red>**DO THIS:**</font> Write the risk as quadratic form. I.e., find the matrix $A$ such that $\sigma = x^\top A x$.

In [17]:
A = sym.Matrix([[0.1**2,0.0018,0.0011],[0.0018,0.1044**2,0.0026],[0.0011,0.0026,0.1411**2]])
A

⎡ 0.01     0.0018      0.0011  ⎤
⎢                              ⎥
⎢0.0018  0.01089936    0.0026  ⎥
⎢                              ⎥
⎣0.0011    0.0026    0.01990921⎦

<font color=red>**DO THIS:**</font> Choose your portfolio and explain why you choose this one. Remember, we want to get high expected return and low risk, and it is difficult to get both. 

Maximize return - factor * risk 

## Smallest Risk
If you are not risky, you can choose the protfolio with the smallest risk. Then the optimization problem is to minimize the risk
$$\min_x~ x^\top A x \mbox{ subject to } x_1+x_2+x_3 = 1$$

<font color=red>**DO THIS:**</font> Solve this problem using the Lagrangian multiplier from the pre-class assignment. 

In [20]:
#####Start your code here #####
C = np.matrix([1,1,1])
d = 1
left = np.zeros((4,4))
left[:3,:3] = 2*A
left[3,:3] = C
left[:3,3] = C
left

right = np.zeros((4,1))
right[3] = d
right

per = np.linalg.solve(left,right)
per
#####End of your code here#####

array([[ 0.44113344],
       [ 0.36568794],
       [ 0.19317862],
       [-0.01056414]])

<font color=red>**QUESTION:**</font> What is the expected return? 

In [37]:
r = np.array([0.0427,0.0015, 0.0285])
r = r.reshape(1,3)

np.matmul(per[:3].T, r.T)

array([[0.02489052]])

## Efficient Portfolios

However, this approach may be too conservative, and we can not make enough profit. 
We know that for a expected return, we may have many portfoilios and we want to choose the one with smallest risk. 
The problem becomes


$$\min_x~ x^\top A x \mbox{ subject to } x_1+x_2+x_3 = 1,~x_1\mu_1+x_2\mu_2+x_3\mu_3 = 0.0427$$

The target return is the same of Microsoft, but we may not purchase only the Microsoft because it is risky. We can find a good portfolio to reduce the risk.
<font color=red>**DO THIS:**</font> Solve this problem using the Lagrangian multiplier from the pre-class assignment. 

In [43]:
#####Start your code here #####

C = np.matrix([[1,1,1],[0.0427,0.0015,0.0285]])
d = np.matrix([[1],[0.0427]])
left = np.zeros((5,5))
left[:3,:3] = 2*A
left[3:5,:3] = C
left[:3,3:5] = C.T
left

right = np.zeros((5,1))
right[3:5] = d
right

per = np.linalg.solve(left,right)
per

#####End of your code here#####

array([[ 0.82752285],
       [-0.09071021],
       [ 0.26318736],
       [-0.00184483],
       [-0.35030637]])

<font color=red>**QUESTION:**</font> What is the risk for your portfolio? Is this smaller than the one with Microsoft only (the risk for Microsoft only is 0.01)?

In [45]:
x = per[:3]
x.T*A*x

[0.00840145619488353]

## Efficient Portfolios Frontier

The previous two portfolios are equally good, and it depends on the people who choose it. 
In fact, there are many this type of portfolios because we can change the target expected return. 
By changing the target expected return, we can obtain many different portfolios. 
When you increase the target expected return, you will also increase the risk. 

There is another way to balance the rish and expected return. Because you want to minimize the risk and increase the expected return. We can choose to solve 

$$\min_x~ x^\top A x -\alpha (x_1\mu_1+x_2\mu_2+x_3\mu_3) \mbox{ subject to } x_1+x_2+x_3 = 1.$$
Minimize the negative return is the same as increase the return. The new parameter $\alpha\geq 0$ is use to balance the risk and return. 
A small $\alpha$ means that you care more on the risk. $\alpha=0$ corresponds the minimum risk case. 
A large $\alpha$ means that you care more on the return. $\alpha\rightarrow +\infty$ corresponds to the maximum return.

<font color=red>**DO THIS:**</font> Solve this problem using the Lagrangian multiplier from the pre-class assignment with $\alpha$ you choose. 

In [7]:
#####Start your code here #####

#####End of your code here#####

-----
### Congratulations, we're almost done!

Now, you just need to submit this assignment by uploading it to the course <a href="https://d2l.msu.edu/">Desire2Learn</a> web page for today's dropbox (Don't forget to add your names in the first cell).


&#169; Copyright 2018,  Michigan State University Board of Trustees